// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2hGe6rSiRxkLC72QahrtkfVKj_jthwZQ',
    appId: '1:797242528895:web:8d36d6f952e113e1cedb4a',
    messagingSenderId: '797242528895',
    projectId: 'chat-3d603',
    authDomain: 'chat-3d603.firebaseapp.com',
    storageBucket: 'chat-3d603.firebasestorage.app',
    measurementId: 'G-62GZB0JRPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpRllKcMlJPuTqt5tob1W3JA_I95wEpf4',
    appId: '1:797242528895:android:9f66edf021502762cedb4a',
    messagingSenderId: '797242528895',
    projectId: 'chat-3d603',
    storageBucket: 'chat-3d603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjmtMW9cUDTfNNi5VDdtAmCmSYUhTxGjI',
    appId: '1:797242528895:ios:e603b6e5eae1a4a6cedb4a',
    messagingSenderId: '797242528895',
    projectId: 'chat-3d603',
    storageBucket: 'chat-3d603.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );
}
